### ISSUE TITLE
Release with package.json main field fix.

### ISSUE THREAD

**Issue by davidlehn** [awwright/node-iri#2]
Some JSON-LD tooling we have is using this package through `rdfa` and now Node.js 16+ complains about the typo in the `package.json` `main` field.  It's fixed in the repo code.  A 1.3.1 would based off of master would be appreciated.

**Comment by awwright** [comment]
Ah yes, I've intended to fix that, thanks for filing an issue.

**Comment by awwright** [comment]
@davidlehn I pushed out an update, but can you please confirm for me which package is depending on `iri`?

**Comment by davidlehn** [comment]
It's `rdfa` and `rdf` depending on `iri`.  Looks like you got the `rdf` fix release out too.  Thanks!

**Comment by awwright** [comment]
@davidlehn If you have feedback on the "rdfa" module, by all means, please let me know. It's been on a little bit of a hiatus recently, but it does all the heavy lifting for https://github.com/awwright/rdfa-template
